### PR TITLE
dev-dotnet/dotnet-cli-1.1.1 version bump

### PR DESCRIPTION
**Pull request by ezavaleta**
New ebuild for .NET Core SDK with .NET Core 1.0.4 and .NET Core 1.1.1

### CODE REVIEW

**Comment by ezavaleta** [comment]
To be able to merge this ebuild `FEATURES="-sandbox -usersandbox"` is required because `dotnet` command hangs with `sandbox`.

**Comment by josolanes** [comment]
Hi @ezavaleta - using layman, I'm not seeing 1.1.1 show up after a layman -S

eix reports, for dotnet-cli:

server josh # eix -s dotnet-cli
[I] dev-dotnet/dotnet-cli [1]
     Available versions:  (~)1.0.0_pre2_p003121 (~)1.0.0_pre2_p003131
     Installed versions:  1.0.0_pre2_p003131(11:49:39 PM 02/12/2017)
     Homepage:            https://www.microsoft.com/net/core
     Description:         .NET Core cli utility for building, testing, packaging and running projects

[1] "dotnet" /var/lib/layman/dotnet


equery:
server josh # equery meta dotnet-cli
 * dev-dotnet/dotnet-cli [dotnet]
Maintainer:  dotnet@gentoo.org
             Gentoo Dotnet Project
Upstream:    None specified
Homepage:    https://www.microsoft.com/net/core
Location:    /var/lib/layman/dotnet/dev-dotnet/dotnet-cli
Keywords:    1.0.0_pre2_p003121:0:
Keywords:    1.0.0_pre2_p003131:0: ~amd64
License:     MIT



Did I possibly miss a step somewhere that allows installing 1.1.1? I did add FEATURES="-sandbox -usersandbox" to make.conf

Thanks in advance,
Josh

**Comment by mpkh** [comment]
@josolanes layman remote is different than github, sometimes I forget to synchronize them, fixed now.

**Comment by josolanes** [comment]
Thanks @mpkh - that fixed it!

**Comment by vanthome** [comment]
For me it hangs infinitely here:

```
System.Private.CoreLib.dll build unsupported.
Nuget package generation unsupported.
Repo successfully built.
Product binaries are available at /var/tmp/portage/dev-dotnet/dotnet-cli-1.1.1/work/coreclr-1.0.6/bin/Product/Linux.x64.Release
Restoring BuildTools version 1.0.26-prerelease-01121-01...
```

**Comment by ezavaleta** [comment]
@vanthome `FEATURES="-sandbox -usersandbox"` is required.

**Comment by mpkh** [comment]
@ezavaleta note that there are ebuild syntax to resolve that in a bit better way, `addwrite` for example

**Comment by ezavaleta** [comment]
@mpkh Yes, I know but I couldn't find which paths `dotnet` command needs write permissions or even if it is filesystem related. I tried giving write permissions for `${HOME}/.dotnet/` and `${HOME}/.nuget/` but it still hangs.

**Comment by vanthome** [comment]
for me it works now

**Pull request merged**
