### PR TITLE
additional patch for mono

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
see https://github.com/gitextensions/gitextensions/issues/2710 for details

### CODE REVIEW

**Comment by Heather** [comment]
@ArsenShnurkov thank you! May we have it for mono-4.2.1.102 either?
 https://github.com/gentoo/dotnet/blob/master/dev-lang/mono/mono-4.2.1.102.ebuild

**Comment by Heather** [comment]
Also patch name is very confusing - may you at least add comment line in ebuild?

**Comment by Heather** [comment]
`dev-lang/mono/mono-4.2.1.91.ebuild → dev-lang/mono/mono-4.2.1.60-r1.ebuild` - it's because mono 4.2.1.60 was only in your local space so in this repository first version of 4.2.1.60 will be -r1 :)

**Comment by ArsenShnurkov** [comment]
i also submitted this patch to mono - https://github.com/mono/mono/pull/2273, but you are significantly faster :)

**Comment by Heather** [comment]
If You Want To Be Okay Visit GitHub Everyday

**Comment by Heather** [comment]
seriously I hope they will accept it either :+1:

**Pull request merged**
