### PR TITLE
added monodevelop-5.9.4.5 ebuild

### PR DESCRIPTION
**Pull request by chalucha**
Just used previous ebuild and changed workdir.
Compiled and run fine, didn't test all features

### CODE REVIEW

**Comment by ArsenShnurkov** [comment]
Thanks!

Btw, what prevent's it from bumping to 5.9.5.5 ?

**Comment by chalucha** [comment]
That version is not on the used url. But I'm creating an ebuild for it now (changing the download url to githubs) and will make other PR

**Comment by chalucha** [comment]
well I tried, but the source archive on 
https://github.com/mono/monodevelop/releases

is totally different to archives in
http://download.mono-project.com/sources/monodevelop/

even the same versions.
So it would need a bit of hacking of the ebuild which is over my skills ;-)

**Comment by ArsenShnurkov** [comment]
the second archive is prepared with make dist command

**Comment by chalucha** [comment]
thx, I'll look at it

**Comment by Heather** [comment]
@chalucha I guess for github releases it should build with autotools, alike with live package

**Pull request merged**
