### PR TITLE
media-gfx/pinta-1.6

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
This ebuild work on my machine,
but i have some differences from dotnet overlay:
1) mono-addins-1.0 should be fixed to work with mono >4 (i.e. should choose mcs instead of gmcs by default) - see https://github.com/gentoo/dotnet/issues/92
2) may be gtk-sharp-module.eclass should be patched (I am unsure about this)
see https://github.com/gentoo/dotnet/issues/91

### CODE REVIEW

**Comment by Heather** [comment]
@ArsenShnurkov why does pinta need mono-addins.... I will try to find time to test it

**Comment by ArsenShnurkov** [comment]
> why does pinta need mono-addins

It really provides an ability to create your own addin, i checked :)

**Comment by ArsenShnurkov** [comment]
pinta-1 6

**Comment by Heather** [comment]
@ArsenShnurkov may you try to build with `gtk-sharp-2.99` and yes, we should do something with `mono-addins`

**Comment by Heather** [comment]
and better don't use `~` for deps, fix `gtk-sharp` with slot `2` if it will fails with `3`

**Comment by ArsenShnurkov** [comment]
I added new commit according to your requirements

**Comment by Heather** [comment]
@ArsenShnurkov thank you

**Pull request merged**
