### PR TITLE
dev-dotnet/msbuild, fix 310

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
May be i forgot to move something, please test it

### CODE REVIEW

**Comment by genterminl** [comment]
@mpkh Sorry, I'm not sure what (if anything) I can do to help here.  I was able to build msbuild from the first link in issue #310, which I think is different from PR 310 (and I'll be glad to share how, if it would help anyone) but I'm not sure where to go beyond that, and I don't really follow the rest of the posts in that issue, and how it relates to this PR.

**Comment by genterminl** [comment]
I'm trying to work on this, and I've gotten my own overlay to include this PR, but just starting, msbuild needs dev-dotnet/buildtools, which is not in the dotnet overlay.  I don't know if that's what you might be missing, but might this be trying to do too much at once?

**Comment by mpkh** [comment]
yes, dev-dotnet/buildtools seems missing

**Comment by genterminl** [comment]
@mpkh @ArsenShnurkov 
Good news; I copied dev-dotnet/buildtools from the shnurise overlay, and I also had to copy mono-pkg-config.eclass, but with those present, emerge msbuild completed without error.

**Comment by ArsenShnurkov** [comment]
I didn't understood note about mono-pkg-config.eclass - it is <a href="https://github.com/gentoo/dotnet/pull/328/files#diff-8b1314bed8d6ff8da9af66e91ac9f308">included into PR</a>

**Comment by mpkh** [comment]
@ArsenShnurkov nuget is masked in main tree for removal (will be removed in near time and then unmasked) from there, dotnet stack in tree is a bit outdated, not very tested and have many issues. we should add package.unmask with that package in overlay (add it to profiles/package.unmask file)

**Comment by genterminl** [comment]
@ArsenShnurkov I think the eclass issue was because I was building buildtools in my local overlay and the eclass was in my own dotnet overlay.  I suspect ebuild or emerge only looks for eclass files in the same tree/overlay as the ebuild it is working on.

@mpkh I will try to remove all the new packages, update my overlay and try again.  I will let you know if I succeed or if I run out of time before vacation next week.

**Comment by ArsenShnurkov** [comment]
> I suspect ebuild or emerge only looks for eclass files in the same tree/overlay as the ebuild it is working on.

yes, it looks only in the same overlay and it's masters (if repository C specifies masters of "B E", then eclasses will be searched for first in C, and if not found, then E, and if not found, then B)

**Comment by genterminl** [comment]
@mpkh @ArsenShnurkov After cleaning everything out and updating to the current PR, everything emerged cleanly.
One questions - doing "msbuild /version" gives "Microsoft (R) Build Engine version 1.0.27.0 for .NET Framework" with a final 1.0.27.0 with no trailing LF.  That command with the version I compiled from the original tarball says "Microsoft (R) Build Engine version 15.5.0.0 ( Fri Sep 22 14:04:35 EDT 2017) for Mono"  I don't know if it actually makes any difference whether it says for .NET or for mono, but I'm curious why the large difference in version numbers - is it something about .NET vs mono?

**Comment by ArsenShnurkov** [comment]
no, it's not about .net vs mono. It's about different build process (it is possible to show any version in gentoo)

**Comment by genterminl** [comment]
That's fine - I don't actually care what version it shows.  I'm just trying to understand how the build process can change the version number displayed.  I would expect that to be internal to the source code, but there is certainly plenty about dotnet and mono I just don't understand.  Note also it's not just the different between 15.3 and 15.5, but 1.0.27.0.  It's like it is from a completely different software.  Anyway - this step is done.

**Comment by genterminl** [comment]
Sorry, but there seems to be something I don't understand.  When should I expect to see this commit in the dotnet overlay?

**Comment by ArsenShnurkov** [comment]
What you are asking about? New changes will be available, when they will be required for me. If you need your changes you are free to implement them.

**Comment by genterminl** [comment]
I created this PR, and it was accepted and merged 27 days ago.  My question is where was it merged to?  I thought that meant it would end up in the gentoo dotnet overlay.  If I'm mistaken about that, then where can I figure out how all these pieces work together?  (For this PR, I do already have it implemented in my local overlay, so there is no rush, I'm just trying to understand the real implications of having the PR accepted.)

**Comment by ArsenShnurkov** [comment]
your repository is far behind the master branch of dotnet overlay
you need to read on <a href="https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository">how to catch up upstream repository</a>

**Comment by genterminl** [comment]
I'll fix that, but it won't help with what I'm asking, although perhaps I haven't explained myself well enough.  Once my PR was accepted, I removed my own overlay from my local layman, so I'm now using only the official Gentoo dotnet overlay.  Isn't that where these PRs should eventually end up?  If not, then how does any of this work help anyone before stuff (eventually) makes it into the main tree?

**Comment by ArsenShnurkov** [comment]
@mpkh, please help me with translation to russian, I don't fully understand the question.
@genterminl, all PR-s (both accepted and not) are listed <a href="https://github.com/gentoo/dotnet/pulls">here</a>. If you don't see your PR in this list, then you made something wrong duting it's creation...

**Comment by genterminl** [comment]
I apologize for not being clear enough.  I do not have a problem with my own fork of the overlay.  (I will probably delete and create it again if I need to, I have no work which would be lost.   If my own PR appears missing, it is probably because I updated incorrectly.)  I only have the gentoo/dotnet overlay added to layman.  I removed my own overlay once my PRs were accepted.  

My question is not about any particular PR.  It is more general.  I see many recent merged PRs and other commits when I look at  https://github.com/gentoo/dotnet.  Even after doing "layman -s" again, when I look in my local clone of the dotnet overlay (url = https://anongit.gentoo.org/git/proj/dotnet.git) the most recent commit I see is from Aug 2.  I want to understand the relation between those two repositories - because I thought they were supposed to be the same thing.  I think there is just something I don't understand about how the overlays work.

**Comment by ArsenShnurkov** [comment]
I don't know about that, because i use only github's version of repository

**Comment by genterminl** [comment]
OK.  @mpkh can you explain?  If not, where should I look for more information?

For more background, the anongit version is what is listed in "layman -L" and what I think most people would use.  If this is not getting the most recent updates approved by the team, then I think that is a problem.  I will keep looking.

**Comment by ArsenShnurkov** [comment]
the proper solution is to become a gentoo developer and synchronize your update yourself

**Comment by mpkh** [comment]
I guess you can update things by yourself even without being developer
@genterminl layman repository address is different (it's on git.gentoo.org), I sometimes forget to synchronize this and that repository, just made it. We can change address to github later but not sure if many people really need that.

**Comment by genterminl** [comment]
@mpkh Thanks.

**Pull request merged**
