### PR TITLE
remove herd lines

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
cd /var/lib/layman/dotnet
find . -iname "metadata.xml" -print0 | xargs -0 grep -l herd | xargs sed -i "/herd/d"

### CODE REVIEW

**Comment by Heather** [comment]
@ArsenShnurkov for what?

**Comment by Heather** [comment]
I see it comes from here: https://github.com/gentoo/gentoo/commit/cfd93d768e79a349f1e762b92773190295c36980

**Comment by Heather** [comment]
nodes with `<maintainer type="project">` should be added either

**Comment by ArsenShnurkov** [comment]
Which mailing list our project uses? :)

**Comment by ArsenShnurkov** [comment]
I doubt that this is good idea to write this email, because I don't understand how it work.
This article https://wiki.gentoo.org/wiki/Project:Infrastructure/Developer_E-Mail
not explain what happen when users send mail to that email

**Comment by ArsenShnurkov** [comment]
side note: Java is component of Gentoo, and mono/CLI is not:
https://bugs.gentoo.org/describecomponents.cgi?product=Gentoo%20Linux

**Comment by ArsenShnurkov** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=575288
https://bugs.gentoo.org/show_bug.cgi?id=575290

**Pull request merged**
