### PR TITLE
Proper fix of NuGet.Core dependency is completed

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
(finally)

### CODE REVIEW

**Comment by ArsenShnurkov** [comment]
The repoman check is failed, but it was the same earlier, no my new errors

**Comment by Heather** [comment]
@ArsenShnurkov may you rebase commits to one with proper message?

**Comment by Heather** [comment]
@ArsenShnurkov thank you!

**Comment by Heather** [comment]
@ArsenShnurkov also I'm not sure but during build process it seems like it builds in Debug, I think we should provide Release build.

**Comment by dorvan** [comment]
hi guys, i see you already works together.

**Pull request merged**
