### PR TITLE
Moving patch to stable ebuild

### PR DESCRIPTION
**Pull request by ArsenShnurkov**

### CODE REVIEW

**Comment by Heather** [comment]
@ArsenShnurkov thank you. can you build monodevelop with this version of mono?

**Comment by ArsenShnurkov** [comment]
You already asked this in that thread - https://github.com/gentoo/dotnet/issues/71  I will answer, when i will have facts.

**Comment by ArsenShnurkov** [comment]
Basic functions of monodevelop works (I was able to debug test site)

**Comment by Heather** [comment]
@ArsenShnurkov thank you

**Pull request merged**
