### PR TITLE
Add mono 4.0.1.34

### PR DESCRIPTION
**Pull request by bsagal**

### CODE REVIEW

**Comment by Heather** [comment]
@bsagal thank you but your add_missing_vb_portable_targets patch modification affects older ebuilds, is it safe here? it's better to create new patch with specified version.

Btw mono 4.0 and 4.0.1 have serious bug with calls to .NET 2.0 3.0 3.5 libs, it's fixed in master, do you know if it's fixed here or not? It should be added to https://github.com/gentoo/dotnet/blob/master/profiles/package.mask and unmasked if bug is gone, it was fixed in master but 4.0.1 is another branch and we can't be sure if fix is ported

**Comment by bsagal** [comment]
The patch only applies to 4.0.1.34, it add 2 files missing from the tarball, (see http://osdir.com/ml/general/2015-05/msg20808.html). what do you suggest a better name for the patch.

I do not know if it is fixed, do you have a reference to the upstream bug/fix for me to try and find out? please add to the mask if needed.

**Comment by Heather** [comment]
@bsagal my fault about patch, diff highlighting for diff files tricked me.

 - bug reference here: https://bugzilla.xamarin.com/show_bug.cgi?id=29665
 - fix commit here: https://github.com/mono/mono/commit/ae495e8bd485f48ecdb7e53d7e98771220f31997

maybe https://github.com/gentoo/dotnet/blob/master/profiles/package.mask should be
`&& (>=dev-lang/mono-4.0 <=dev-lang/mono-4.1)` ?

**Comment by bsagal** [comment]
looked at the tarball and seems to also have the bad version of the file, so should be masked

**Comment by Heather** [comment]
@bsagal may you modify packages.mas to `&& (>=dev-lang/mono-4.0 <=dev-lang/mono-4.1)` (if I didn't failed in syntax) in terms of this pull request

**Comment by bsagal** [comment]
I get an Invalid atom error for: && (>=dev-lang/mono-4.0 <=dev-lang/mono-4.1),

is =dev-lang/mono-4.0* alright

**Comment by Heather** [comment]
@bsagal yes

**Comment by Heather** [comment]
:+1:

**Pull request merged**
