### PR TITLE
draft ebuild for X.PagedList

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
4 packages are installed from binary code instead of installing from sources:
- Microsoft.AspNet.Mvc (depends on Microsoft.AspNet.Razor, Microsoft.AspNet.WebPages)
- Microsoft.AspNet.Razor
- Microsoft.AspNet.WebPages (depends on Microsoft.Web.Infrastructure)
- Microsoft.Web.Infrastructure

### CODE REVIEW

**Comment by Heather** [comment]
@ArsenShnurkov are you sure you want package name with capital letters?

**Comment by ArsenShnurkov** [comment]
i dont know guidelines against that. do you?

**Comment by Heather** [comment]
@ArsenShnurkov common sense

**Comment by ArsenShnurkov** [comment]
I agree, that there exist an idea "let's make anything lowercase, and user will have less typos".
But the original names of the assemblies are case sensitive.
Example of mixed case assembly name: System.IO.FileSystem.AccessControl.dll
And my idea was just replace all dots to minuses...

so I propose to merge in camel case

**Pull request merged**
