### PR TITLE
dev-util/mono-tools: add gtkhtml to IUSE

### PR DESCRIPTION
**Pull request by Hummer12007**

### CODE REVIEW

**Comment by mpkh** [comment]
what is it?

**Comment by Hummer12007** [comment]
An alternative (to webkitgtk) html renderer. Hm, it seems that this ebuild requires some more work. On it

**Comment by mpkh** [comment]
@Hummer12007 yes, your change at the moment only adds ability to enable use flag which is doing nothing so far, it must be provided to configure section maybe, for now I will close PR.

**Comment by Hummer12007** [comment]
Ah, well, I did some research, and it turned out, that support for gtktml is pretty much pointless in the ebuild (as it requires gtkhtml-sharp, which is pretty much dead and not here), so the right thing to do would be to simply remove the check for the use flag, and thus the webkit use flag can be removed as well, as one is required.

**Pull request closed without merging**
