### PR TITLE
Add monodevelop-5.10.3.51

### PR DESCRIPTION
**Pull request by piedar**

### CODE REVIEW

**Comment by Heather** [comment]
Thanks! Does it work?

**Comment by piedar** [comment]
It compiles and runs.  It can load a solution and restore NuGet packages.  I did not test very thoroughly, but nothing appeared to be missing.

**Comment by piedar** [comment]
And I started on 6.1, but did not get very far due to https://bugzilla.xamarin.com/show_bug.cgi?id=39191.

**Comment by Heather** [comment]
@piedar it's great, I really wanted to get `6.1` but faced many complicated things there :+1:

**Pull request merged**
