### PR TITLE
some fixes was moved into upstream

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
I propose to modify patch like this

### CODE REVIEW

**Comment by ArsenShnurkov** [comment]
build fault is a bug in another ebuild

**Comment by Heather** [comment]
@ArsenShnurkov what?

**Comment by ArsenShnurkov** [comment]
That!

RepoMan scours the neighborhood...

  IUSE.invalid [fatal]          1

   dev-lang/fsharp/fsharp-9999.ebuild: fsharp4

  dependency.bad [fatal]        442

**Comment by Heather** [comment]
I've made manual merge, will push after test

**Pull request merged**
