### PR TITLE
Bump dev-lang/fsharp to v4.0.1.15

### PR DESCRIPTION
**Pull request by piedar**
No ebuild changes required.
I noticed it takes forever to build all those different profiles.  Maybe we could skip some of them?

### CODE REVIEW

**Comment by mpkh** [comment]
not sure

**Comment by mpkh** [comment]
@piedar btw please keep only one actual ebuild, I think there is no need to keep old one

**Comment by piedar** [comment]
OK, I will keep that in mind for next time.

**Comment by mpkh** [comment]
bumped in main tree, this one could be removed for a while.

**Pull request merged**
